apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webapp
    app: webapp
  name: webapp
spec:
  imagePullSecrets:
  - name: ghcr-secret
  containers:
  - image: ghcr.io/guentherloesel/pi-mail-monitor/web:subpath-test
    name: webapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
