apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport
spec:
  selector:
    app: webapp # This label should match your NGINX pod's label
  type: NodePort
  ports:
    - port: 80            # Target port on the NGINX pod
      targetPort: 80
      nodePort: 30000