apiVersion: batch/v1
kind: CronJob
metadata:
  name: mail-parser
spec:
  schedule: "*/15 * * * *"
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: ghcr-secret
          containers:
          - name: mail-parser-container
            image: ghcr.io/guentherloesel/pi-mail-monitor/parser:0.5.0
            volumeMounts:
            - mountPath: "/var/tmp/mail"
              name: mail-volume
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: job-db
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: job-db
                  key: pass
            - name: DB_NAME
              value: "jobs_db"
            - name: DB_SERVICE
              value: "couch-db-svc-couchdb"
            - name: NATS_SERVER
              value: "nats://nats.pi-mail-monitor.svc.cluster.local:4222"
            - name: NATS_SUBJECT
              value: "vacancies"
          volumes:
          - name: mail-volume
            persistentVolumeClaim:
              claimName: mail-pvc
          restartPolicy: OnFailure