apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webapp
    app: webapp
  name: webapp
spec:
  imagePullSecrets:
  - name: ghcr-secret
  containers:
  - name: webapp
    image: ghcr.io/guentherloesel/pi-mail-monitor/web:0.4.0
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: job-db
          key: user
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: job-db
          key: pass
    - name: DB_NAME
      value: "jobs_db"
    - name: DB_SERVICE
      value: "couch-db-svc-couchdb"
    - name: DB_PORT
      value: "5984"
    - name: NGINX_PORT
      value: "80"
    volumeMounts:
    - mountPath: /etc/nginx/conf.d/couchdb-proxy.conf
      name: nginx-couchdb-config
      subPath: couchdb-proxy.conf
    - mountPath: /etc/nginx/html/index.html
      name: nginx-index-configmap
      subPath: index.html

  initContainers:
  - name: init-nginx-config
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      apk add --no-cache gettext && \
      export DB_CREDENTIALS=$(echo -n "${DB_USER}:${DB_PASS}" | base64) && \
      envsubst '$DB_SERVICE $DB_PORT $DB_CREDENTIALS' < /config/couchdb-proxy.conf > /mnt/nginx/couchdb-proxy.conf
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: job-db
          key: user
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: job-db
          key: pass
    - name: DB_SERVICE
      value: "couch-db-svc-couchdb"
    - name: DB_PORT
      value: "5984"
    volumeMounts:
    - mountPath: /mnt/nginx
      name: nginx-couchdb-config
    - mountPath: /config/couchdb-proxy.conf
      name: nginx-config-template
      subPath: couchdb-proxy.conf

  volumes:
  - name: nginx-couchdb-config
    emptyDir: {}
  - name: nginx-config-template
    configMap:
      name: nginx-couchdb-config
  - name: nginx-index-configmap
    configMap:
      name: nginx-index-html