apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="de">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>CouchDB Detaildaten anzeigen</title>
    </head>
    <body>
      <button id="fetchButton">Daten abrufen</button>
      <table id="dataTable" border="1">
        <thead>
          <tr>
            <th>ID</th>
            <th>Revision</th>
            <th>Delivery Date</th>
            <th>Text</th>
            <th>Job Description Link</th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>

      <script>
        document.getElementById("fetchButton").addEventListener("click", function() {
          fetch('http://bigberry/pi-mail-monitor/couchdb/jobs_db/_all_docs')
            .then(response => {
              if (!response.ok) {
                throw new Error('Network response was not ok');
              }
              return response.json();
            })
            .then(data => {
              const tableBody = document.querySelector("#dataTable tbody");
              tableBody.innerHTML = ""; // Tabelle leeren

              data.rows.forEach(row => {
                // Für jede ID und jeden Key die detaillierten Daten abrufen
                fetch(`http://bigberry/pi-mail-monitor/couchdb/jobs_db/${row.id}`)
                  .then(detailResponse => {
                    if (!detailResponse.ok) {
                      throw new Error('Network response was not ok');
                    }
                    return detailResponse.json();
                  })
                  .then(detailData => {
                    // Zeile für die Detaildaten erstellen
                    const tableRow = document.createElement("tr");

                    // ID-Zelle
                    const idCell = document.createElement("td");
                    idCell.textContent = detailData._id;
                    tableRow.appendChild(idCell);

                    // Revision-Zelle
                    const revCell = document.createElement("td");
                    revCell.textContent = detailData._rev;
                    tableRow.appendChild(revCell);

                    // Delivery Date-Zelle
                    const deliveryDateCell = document.createElement("td");
                    deliveryDateCell.textContent = detailData.delivery_date;
                    tableRow.appendChild(deliveryDateCell);

                    // Text-Zelle
                    const textCell = document.createElement("td");
                    textCell.textContent = detailData.text;
                    tableRow.appendChild(textCell);

                    // Job Description Link-Zelle
                    const linkCell = document.createElement("td");
                    const link = document.createElement("a");
                    link.href = detailData.job_description_link;
                    link.textContent = "Zur Jobbeschreibung";
                    link.target = "_blank";
                    linkCell.appendChild(link);
                    tableRow.appendChild(linkCell);

                    tableBody.appendChild(tableRow); // Zeile zur Tabelle hinzufügen
                  })
                  .catch(error => console.error('Es gab ein Problem mit dem Detail-Fetch:', error));
              });
            })
            .catch(error => console.error('Es gab ein Problem mit der Fetch-Operation:', error));
        });
      </script>
    </body>
    </html>