FROM python:3.11-slim

COPY ./parser/emailParser.py /app/emailParser.py

# Set the working directory
WORKDIR /app

# Install dependencies if needed (otherwise, skip this line)
# RUN pip install -r requirements.txt

CMD ["python", "emailParser.py"]