name: Build and push parser Image to ghcr.io
run-name: Build and push parser Image • ${{ github.repository }} ∷ ${{ github.ref }} ∷ ${{ inputs.image-tag }} to ghcr.io

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: additional image-tag
        required: false
        default: ''
        type: string
  release:
    types:
      - created

env:
  ADDITIONAL_IMAGE_TAG: ""

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU for multi-architecture support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.parser
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/parser:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}/parser:${{ inputs.image-tag }}
          build-args: |
            TARGETPLATFORM=linux/arm64
          labels: |
            org.opencontainers.image.licenses=MIT
          package-visibility: private

      - name: Display Docker image info
        run: |
          docker manifest inspect ghcr.io/${{ github.repository }}/parser:${{ github.ref_name }}